-- Generated by nwg-displays on 2026-05-31 at 15:59:35. Do not edit manually.

hl.monitor({
    output = "eDP-2",
    mode = "2560x1600@240.0",
    position = "0x440",
    scale = 1.6
})
hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60.0",
    position = "1600x0",
    scale = 1.5
})
