# Style
set -g status-style bg=default
set -g message-style bg=green,fg=black,bold
set -g mouse on
setw -g window-status-current-style fg=black,bg=green,bold
setw -g window-status-current-format ' #I:#W '
setw -g window-status-style fg=white,bg=default

# Options
set -s set-clipboard on
set -g allow-passthrough on
set -as terminal-features ',xterm-256color:clipboard'

# Keybinds
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

