# Style
set -g status-style bg=default
set -g message-style bg=green,fg=black,bold
setw -g window-status-current-style fg=black,bg=green,bold
setw -g window-status-current-format ' #I:#W '
setw -g window-status-style fg=white,bg=default

# Options
set -s set-clipboard on
set -g allow-passthrough on
set -as terminal-features ',xterm-256color:clipboard'

# Keybinds
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

bind C-w resize-pane -x 80 # Set pane width to 80

# Switch panes with Ctrl+Shift+h/j/k/l
bind-key -n C-S-h select-pane -L
bind-key -n C-S-j select-pane -D
bind-key -n C-S-k select-pane -U
bind-key -n C-S-l select-pane -R
